package fr.univtln.bruno.samples.jaxrs.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.java.Log;
import org.eclipse.collections.api.map.primitive.MutableLongObjectMap;
import org.eclipse.collections.impl.factory.primitive.LongObjectMaps;

@Log
@Getter
@Setter
@FieldDefaults(level = AccessLevel.PRIVATE)
@NoArgsConstructor(staticName = "of")
public class BiblioModel {
    private static long lastId = 0;
    MutableLongObjectMap<Auteur> auteurs = LongObjectMaps.mutable.empty();

    public Auteur putAuteur(Auteur auteur) {
        auteur.id = ++lastId;
        return auteurs.put(auteur.id, auteur);
    }

    public Auteur updateAuteur(long id, Auteur auteur) {
        return auteurs.put(id, auteur);
    }

    public Auteur removeAuteur(long l) {
        return auteurs.remove(l);
    }

    public Auteur getAuteur(long l) {
        return auteurs.get(l);
    }

    public int getAuteurSize() {
        return auteurs.size();
    }

    public void supprimerAuteurs() {
        auteurs.clear();
    }

    @Builder
    @Getter
    @Setter
    @FieldDefaults(level = AccessLevel.PRIVATE)
    @NoArgsConstructor
    @AllArgsConstructor

    //To enable XML Serialization
    @XmlRootElement
    //Because getterare generated by lombok
    @XmlAccessorType(XmlAccessType.FIELD)
    public static class Auteur {
        @XmlAttribute
        long id;

        String nom;

        String prenom;

        String biographie;
    }
}
